import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const mapPath = path.join(rootDir, "map.png");
const inputPath = path.join(rootDir, "walkmask.png");
const outputPath = path.join(rootDir, "src", "game", "walkmaskGrid.js");

const CELL_SIZE = 4;
const WALKABLE_THRESHOLD = 170;
const CELL_WALKABLE_RATIO = 0.65;

const map = PNG.sync.read(fs.readFileSync(mapPath));
const image = PNG.sync.read(fs.readFileSync(inputPath));

const gridWidth = Math.ceil(map.width / CELL_SIZE);
const gridHeight = Math.ceil(map.height / CELL_SIZE);
const rows = [];

for (let gy = 0; gy < gridHeight; gy += 1) {
  let row = "";
  for (let gx = 0; gx < gridWidth; gx += 1) {
    row += isCellWalkable(image, gx, gy) ? "1" : "0";
  }
  rows.push(row);
}

const fileContents = `// Generated by scripts/generateWalkmaskGrid.mjs from walkmask.png.
// Do not edit this file by hand; update walkmask.png and rerun the generator.

export const WALKMASK_SOURCE_WIDTH = ${map.width};
export const WALKMASK_SOURCE_HEIGHT = ${map.height};
export const WALKMASK_CELL_SIZE = ${CELL_SIZE};
export const WALKMASK_GRID_WIDTH = ${gridWidth};
export const WALKMASK_GRID_HEIGHT = ${gridHeight};

export const WALKMASK_ROWS = Object.freeze([
${rows.map((row) => `  "${row}"`).join(",\n")}
]);

export function isWalkmaskPointWalkable(point) {
  if (
    !Number.isFinite(point?.x) ||
    !Number.isFinite(point?.y) ||
    point.x < 0 ||
    point.y < 0 ||
    point.x > WALKMASK_SOURCE_WIDTH ||
    point.y > WALKMASK_SOURCE_HEIGHT
  ) {
    return false;
  }

  const gridX = Math.min(
    WALKMASK_GRID_WIDTH - 1,
    Math.max(0, Math.floor(point.x / WALKMASK_CELL_SIZE))
  );
  const gridY = Math.min(
    WALKMASK_GRID_HEIGHT - 1,
    Math.max(0, Math.floor(point.y / WALKMASK_CELL_SIZE))
  );

  return WALKMASK_ROWS[gridY][gridX] === "1";
}
`;

fs.writeFileSync(outputPath, fileContents);
console.log(
  `Generated ${path.relative(rootDir, outputPath)} (${gridWidth}x${gridHeight}) from walkmask.png (${image.width}x${image.height} sampled onto ${map.width}x${map.height})`
);

function isCellWalkable(image, gridX, gridY) {
  const minX = gridX * CELL_SIZE;
  const minY = gridY * CELL_SIZE;
  const maxX = Math.min(map.width, minX + CELL_SIZE);
  const maxY = Math.min(map.height, minY + CELL_SIZE);
  let walkablePixels = 0;
  let totalPixels = 0;

  for (let y = minY; y < maxY; y += 1) {
    for (let x = minX; x < maxX; x += 1) {
      totalPixels += 1;
      if (isSourcePixelWalkable(image, x, y)) {
        walkablePixels += 1;
      }
    }
  }

  return totalPixels > 0 && walkablePixels / totalPixels >= CELL_WALKABLE_RATIO;
}

function isSourcePixelWalkable(image, mapX, mapY) {
  const sourceX = Math.min(
    image.width - 1,
    Math.floor(((mapX + 0.5) / map.width) * image.width)
  );
  const sourceY = Math.min(
    image.height - 1,
    Math.floor(((mapY + 0.5) / map.height) * image.height)
  );
  const pixelIndex = (sourceY * image.width + sourceX) * 4;
  const alpha = image.data[pixelIndex + 3];
  const brightness =
    (image.data[pixelIndex] + image.data[pixelIndex + 1] + image.data[pixelIndex + 2]) / 3;

  return alpha > 12 && brightness >= WALKABLE_THRESHOLD;
}
